# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DKDataTrackKitDemo' do
  
  pod 'DKDataTrackKit', :path => '../'

  target 'DKDataTrackKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DKDataTrackKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
