# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DKDataTrackKitDemo' do
  
  pod 'DKDataTrackKit', :path => '../'
#  pod 'DKCorePodResourceUtil',:git => 'git@gitlab.danke.life:iosGroup/DKCorePodResourceUtil.git',:tag => 'v0.0.1',:inhibit_warnings => true

  target 'DKDataTrackKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DKDataTrackKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
